#!/bin/sh
set -e

os_type=$(uname -s | tr '[:upper:]' '[:lower:]')

# OS specific bootstrap
"$0_$os_type.sh"

# Setup ssh key
if [ ! -f "$HOME/.ssh/id_rsa" ]; then
    # Generate key
    ssh-keygen -t rsa -b 4096

    # Add it to keychain
    ssh-add -K ~/.ssh/id_rsa
fi

# Install osprey
curl -s -L "https://dl.bintray.com/sky-uk/oss-generic/osprey/latest/osprey-latest_${os_type}_amd64.tar.gz" -o /tmp/osprey.tar.gz
mkdir -p "$HOME/.local/bin" && tar -xvf /tmp/osprey.tar.gz -C "$HOME/.local/bin"
chmod +x "$HOME/.local/bin/osprey"

# Setup VS Code extensions
# Shell check
code --install-extension timonwong.shellcheck

# Line sort
code --install-extension Tyriar.sort-lines

# Fish IDE
code --install-extension lunaryorn.fish-ide

# Change the origin of YADM repo to SSH
git --git-dir="$HOME/.yadm/repo.git" remote set-url origin git@github.com:ricardojoaoreis/yadm.git
